config/routes.rb
DaveApp::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  root 'posts#index'
  resources :posts, path: ''

  get 'topic/:tag' => 'posts#tag', as: :tag

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  def self.tags
    posts = Post.all
    tags = posts.map do |post|
      post.tag
    end
    tags.uniq
  end

  def to_param
    self.slug
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :tags
  before_action :find_post, only: [:show, :edit, :update]
  before_action :admin?, except: [:index, :show, :tag]

  def index
    @posts = Post.last(6).reverse
    @title_post = Post.last
  end

  def show
    @posts = Post.where(tag: @post.tag).sort
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    if @post.update_attributes!(post_params)
      redirect_to root_path
    end
  end

  def tag
    @posts = Post.where(tag: params[:tag]).sort
    @title_post = @posts.last
  end

private

  def tags
    @tags = Post.tags
  end

  def post_params
    params.require(:post).permit(:title, :gist, :slug, :hero_image, :thumb_image, :tag, :body)
  end

  def find_post
    @post = Post.find_by_slug(params[:id])
  end

  def admin?
    if current_user.nil?
      redirect_to root_path
    else
      unless current_user.role == "Admin"
        redirect_to root_path
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = [:hard_wrap]
    Redcarpet.new(text, *options).to_html.html_safe
  end

  def tag_count tag
    Post.where(tag: tag).count
  end
end

app/views/layouts/application.html.erb
doctype
html
  head
    title On Another Note...
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    = yield

app/views/layouts/application.slim
html
  head
    title On Another Note... by Dave Woodall
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shared/fonts'
    = render 'layouts/shared/analytics'
    link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"
    meta content="Dave Woodall" name="author"
    meta content="chrome=1" http-equiv="X-UA-Compatible"
    meta content="initial-scale=1.0, user-scalable=no, maximum-scale=1.0" name="viewport"
    meta content="yes" name="apple-mobile-web-app-capable"
    meta content="black" name="apple-mobile-web-app-status-bar-style"


  body.typography
    = yield

    footer
      = render 'posts/footer'

app/views/layouts/shared/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';

  ga('create', 'UA-40303853-1', 'woodalls.me');
  ga('send', 'pageview');

</script>

app/views/layouts/shared/_breadcrumb.slim
.m-breadcrumb
  = link_to root_path do
    i.fa.fa-home
    i.fa.fa-angle-double-right

  - if post.try(:title)
    = link_to "/topic/#{post.tag}" do
      span= post.tag
      i.fa.fa-angle-double-right
    = link_to post.title, post_path(post)

  - else
    = link_to "/topic/#{post.first.tag}" do
      span= post.first.tag

app/views/layouts/shared/_fonts.html.erb
<script type="text/javascript" src="//use.typekit.net/jow5qps.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

app/views/layouts/shared/_tag_list.slim
.post-tags
  .tag-title
    h4 Topics
  .tag-list
    ul#tags
      - @tags.sort.each do |tag|
        li= link_to tag_path(tag) do
          => tag
          span= "(#{tag_count tag})"
  = link_to root_path do
    span= "all ("
    i.fa.fa-home
    span= ")"

app/views/layouts/shared/_user_widget.html.erb
<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p>
  <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/posts/_footer.slim
.l-footer

  .m-footer
    .footer-about
      .footer-title
        h5 Intro
      .footer-copy
        p If you're familiar with Meyers-Briggs then my letters "INTJ" will make sense. If you're not familiar, well it basically means I like learn about a lot of things, in a lot of ways. But more than learn, I like to build, create, design, think, and grow. If I had to summarize myself, I like to think I'm a modern-day Renaissance man as best I know how. I spend my time thinking, building, designing, coding, inventing, and philosophizing. I have been journaling for nearly 20 years, so blogging is a natural extension for the parts of me that I want to keep track of publicly.
      .footer-title
        h5 Topics
      .footer-copy
        p I've built this site from scratch so it can be a little buggy at times. I don't tweet or facebook anymore so most of my posts are simialar in fashion to those sites. Except, nobody but the NSA is watching me :-) The home page shows my 5 most recent posts but everything else after that gets tucked into the topics on the sidebar. If your'e still reading, then we must be related somehow because I can't imagine anyone would really get this far. Thanks for stopping by!
  / 
  /   .footer-column
  /     .footer-about
  /       .footer-title
  /         h5 Users
  /         p.notice= notice
  /         p.alert= alert
  /       .footer-copy
  /         - if user_signed_in?
  /           p
  /             | Welcome
  /             = current_user.email
  /           = link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete
  /         - else
  /           p
  /             | Private area
  /             =< link_to 'sign in.', new_user_session_path
  /   .footer-column
  /     .footer-projects
  /       .footer-title
  /         h5 Projects
  /       .footer-list
  /         ul
  /           li
  /             a href="http://www.hireDave.me" class="footer-link" hireDave
  /           li
  /             a href="http://www.destroyalltasks.com" class="footer-link" Destroy All Tasks
  /           li
  /             a href="http://www.afterburners.mx" class="footer-link" Afterburners
  /           li
  /             a href="http://www.catmathdo.com" class="footer-link" CatMathDo
  /           li
  /             a href="http://www.boulderwebcamp.com" class="footer-link" Boulder Web Camp
  /           li
  /             a href="http://abidinglife.tumblr.com" class="footer-link" Abiding Life
  /   .footer-column
  /     .footer-social
  /       .footer-title
  /         h5 Social
  /       .footer-list
  /         ul
  /           li
  /             a href="https://www.youtube.com/channel/UC6vFDSlJOIEfqfXL7cLAFvw" class="footer-link" youtube
  /           li
  /             a href="http://www.linkedin.com/in/davewoodall" class="footer-link" linkedin
  /           li
  /             a href="http://www.github.com/woodall" class="footer-link" github
  /           li
  /             a href="http://www.dribbble.com/davewoodall" class="footer-link" dribbble

app/views/posts/_form.slim
= form_for @post do |f|
  .input
    =f.text_field :title, placeholder: 'title'
  .input
    =f.text_field :gist, placeholder: 'gist'
  .input
    =f.text_field :slug, placeholder: 'slug'
  .input
    =f.text_field :hero_image, placeholder: 'hero image'
  .input
    =f.text_field :thumb_image, placeholder: 'thumb image'
  .input
    =f.text_field :tag, placeholder: 'tag'
  .input
    =f.text_area :body, placeholder: 'body', rows: 20
  .input
    =f.submit

app/views/posts/_header.slim
.header-shade
.hero-image
  = image_tag(@title_post.hero_image) if @title_post
.l-header
  .m-header
    .header-title
      h1 On another note...
    .header-sub-title
      h2 By Dave Woodall

app/views/posts/_post_snippet.slim
=link_to post_path(post.slug) do
  .pa-archve
    .pa-image
      - if post.thumb_image.empty?
        = image_tag('flatirons_tn.jpg')
      - else
        = image_tag(post.thumb_image)
    .pa-copy
      .pa-tag
        h3= post.tag
      .pa-title
        h3= post.title
      .pa-gist
        h4= post.gist
      .pa-body
        p read more...

app/views/posts/edit.slim
.l-container
  .l-body
    .new-post
      .new-post-title
        h1 Edit Post
      .new-post-form
        = render 'form'

app/views/posts/index.slim
= render 'header'

.l-container
  .l-body
    .m-posts
      = render 'layouts/shared/tag_list'

      .post-articles
        .posts-index
          .posts-hero
            .m-hero-wrapper
              =link_to post_path(@title_post.slug) do
                .ph-title
                  h3= @title_post.title
                .ph-gist
                  h4= @title_post.gist
              .ph-body
                = markdown(@title_post.body)
              .m-image--signature
                = image_tag('dw.png')
          
          .posts-archives
            - @posts.each do |post|
              - unless post.title == @title_post.title
                = render 'post_snippet', post: post

app/views/posts/new.slim
.l-container
  .l-body
    .new-post
      .new-post-title
        h1 New Post
      .new-post-form
        = render 'form'

app/views/posts/show.slim
.header-shade
.hero-image
  = image_tag(@post.hero_image)
.l-header
  .m-header
    .header-title
      h1= @post.title
    .header-sub-title
      h2= @post.gist

.l-container
  .l-body
    = render 'layouts/shared/breadcrumb', post: @post
    .m-posts
      = render 'layouts/shared/tag_list'
      .post-articles
        .posts-index
          .posts-hero
            .m-hero-wrapper
              .ph-body
                p= markdown(@post.body)
              .m-image--signature
                = image_tag('dw.png')
          - if @posts.count > 1
            .posts-archives
              h4 Off that note...
              - @posts.each do |post|
                - unless post.title == @post.title
                  = render 'post_snippet', post: post

app/views/posts/tag.slim
.header-shade
.hero-image
  = image_tag(@title_post.hero_image)
.l-header
  .m-header
    .header-title
      h1= @title_post.tag

.l-container
  .l-body
    = render 'layouts/shared/breadcrumb', post: @posts
    .m-posts
      = render 'layouts/shared/tag_list'
      .post-articles
        .posts-arvchives
          - @posts.each do |post|
            = render 'post_snippet', post: post